1.0.0-dev
starweb/starlit-db-migration pull request #1
Opened 2019-03-11 21:52 UTC by lordrhodos

break out the migration functionality as own library from the `starlit/db` package.

2019-03-15 10:33 UTC, felixsand requested changes
Really nice!
Just a couple of adjustments that I think that we might want to add now that we're breaking this out

2019-03-15 10:33 UTC, felixsand commented on composer.json
> +    },
Should we also add the `branch-alias` here?

2019-03-15 10:33 UTC, felixsand commented on src/Migrator.php
> +    const DIRECTION_UP = 'up';
```suggestion
    private const DIRECTION_UP = 'up';
```

2019-03-15 10:33 UTC, felixsand commented on src/Migrator.php
> +    const DIRECTION_DOWN = 'down';
```suggestion
    private const DIRECTION_DOWN = 'down';
```

2019-03-15 10:33 UTC, felixsand commented on src/Migrator.php
> +    const DIRECTION_DOWN = 'down';
Also, no PHPDocs needed for constants

2019-03-15 10:33 UTC, felixsand commented on src/Migrator.php
> +        if (($direction === self::DIRECTION_UP
This if is way too complex 😱 
Maybe we could break out this logic into `shouldMigrateUp($migration, $toNumber, $direction)` and `shouldMigrateDown($migration, $toNumber, $direction)` instead?

2019-03-15 10:33 UTC, felixsand commented on src/Migrator.php
> +     * @param string $info
PHPDocs can be removed here I think

2019-03-15 20:50 UTC, lordrhodos commented on src/Migrator.php
> +        if (($direction === self::DIRECTION_UP
yes why not simplify this while working at it anyway ;-)

2019-03-18 09:16 UTC, felixsand submitted a review, later dismissed
Perfect! 🎉

2019-03-18 09:29 UTC, merged